// AI-assisted case studies.
//
// Content here was generated by analysing Oksa Satya's GitHub repositories
// (READMEs, module structure, language breakdown, stack) during a Claude Code
// session and then written with marketing-expert discipline: sharp backend
// positioning, concrete and verifiable proof points, NO fabricated metrics.
//
// Most source repos are private; only the AI-written summary is exposed here —
// never the source code. To refresh, re-run the analysis and edit this file.

export interface CaseStudyLink {
  readonly label: string;
  readonly href: string;
}

export interface CaseStudy {
  /** URL slug — drives /projects/[slug] */
  readonly slug: string;
  readonly title: string;
  readonly year: number;
  readonly category: string;
  /** One-line value proposition for the hero. */
  readonly tagline: string;
  /** Short summary used on the portfolio card. */
  readonly summary: string;
  readonly role: string;
  readonly timeframe: string;
  /** Short, chip-friendly tech/positioning highlights. */
  readonly highlights: readonly string[];
  readonly stack: readonly string[];
  /** The problem the project solves (narrative). */
  readonly problem: string;
  /** What was built — concrete, derived from the real repo. */
  readonly solution: readonly string[];
  /** Outcomes framed honestly (capabilities, not invented numbers). */
  readonly results: readonly string[];
  readonly repoVisibility: "public" | "private";
  /** Path under /public. */
  readonly image: string;
  readonly links?: readonly CaseStudyLink[];
}

export const caseStudies: readonly CaseStudy[] = [
  {
    slug: "dexova-erp",
    title: "Dexova — Platform ERP Terintegrasi",
    year: 2025,
    category: "SaaS · ERP",
    tagline:
      "ERP modular untuk bisnis: HRIS, Payroll, POS, dan Inventori dalam satu sistem Go.",
    summary:
      "Platform ERP modular (HRIS, Payroll, POS, Inventori) dengan backend Go hexagonal, fitur AI tertanam, dan integrasi pembayaran Midtrans.",
    role: "Architect & Full-Stack Developer (backend-heavy)",
    timeframe: "2025 – sekarang",
    highlights: [
      "Hexagonal Go",
      "Modular (HRIS · Payroll · POS · Inventori)",
      "AI-powered",
      "Midtrans",
      "gRPC antar-service",
      "Multi-tenant",
    ],
    stack: [
      "Go",
      "PostgreSQL + sqlc",
      "Next.js / TypeScript",
      "Redis",
      "gRPC",
      "SSE (real-time)",
      "Midtrans",
      "OpenAI / Google AI",
      "Docker",
    ],
    problem:
      "Bisnis kecil–menengah menjalankan HR, payroll, kasir, dan stok di tool yang terpisah-pisah — spreadsheet di sini, aplikasi sendiri di sana. Akibatnya data tidak sinkron, rawan salah input, dan sulit mengambil keputusan lintas-divisi. Yang dibutuhkan: satu platform terintegrasi yang tetap terjangkau dan bisa tumbuh seiring bisnis.",
    solution: [
      "Backend Go dengan arsitektur hexagonal dan pemisahan domain yang tegas — empat modul bisnis (Core, HRIS, Inventori, POS), masing-masing dengan query SQL dan migrasi databasenya sendiri sehingga satu modul tidak merusak modul lain.",
      "Aplikasi self-service karyawan (Next.js) untuk absensi, slip gaji, jadwal shift, dan data tim — mengurangi pekerjaan manual tim HR.",
      "Fitur AI tertanam langsung di backend (integrasi OpenAI & Google AI) untuk otomasi dan insight di atas data operasional.",
      "Integrasi pembayaran Midtrans untuk alur transaksi POS, real-time update via Server-Sent Events, dan komunikasi antar-service via gRPC.",
      "Keamanan data tingkat aplikasi: enkripsi data sensitif beserta tooling migrasi enkripsi, dan isolasi data multi-tenant.",
    ],
    results: [
      "Empat modul bisnis (HRIS, Payroll, POS, Inventori) berjalan di atas satu codebase Go yang modular dan konsisten.",
      "Karyawan mendapat portal self-service (absensi, payslip, shift) sehingga proses HR yang tadinya manual jadi mandiri.",
      "Arsitektur hexagonal + batas domain yang jelas membuat penambahan modul baru bisa dilakukan tanpa membongkar yang sudah ada — siap untuk skala.",
    ],
    repoVisibility: "private",
    image: "/assets/images/projects/dexova.png",
  },
  {
    slug: "helixio",
    title: "Helixio — SaaS Produktivitas Multi-tenant",
    year: 2022,
    category: "SaaS",
    tagline:
      "Satu workspace untuk Notes, Kanban, dan sinkronisasi Google Calendar — multi-tenant, dari auth sampai monetisasi.",
    summary:
      "SaaS produktivitas B2B: Notes, Kanban, dan Calendar Sync. Go hexagonal, multi-tenant + RBAC, Google OAuth, dan subscription dengan trial.",
    role: "Backend Engineer & Architect",
    timeframe: "2022",
    highlights: [
      "Hexagonal (Ports & Adapters)",
      "Multi-tenant",
      "RBAC 4 peran",
      "Google OAuth + Calendar",
      "Subscription + trial",
      "CI / codecov",
    ],
    stack: [
      "Go",
      "Gin",
      "PostgreSQL + sqlc",
      "Redis",
      "Google OAuth / Calendar API",
      "SMTP",
      "Docker",
    ],
    problem:
      "Tim kecil butuh satu tempat untuk catatan, papan task, dan kalender — tanpa harus berlangganan banyak tool berbeda. Tantangannya: data tiap workspace harus terisolasi, dan akses harus bisa diatur per peran.",
    solution: [
      "Arsitektur hexagonal (Ports & Adapters) di Go + Gin, memisahkan domain dari infrastruktur sehingga adapter (DB, Google API, SMTP) bisa diganti tanpa menyentuh logika bisnis.",
      "Multi-tenant dengan isolasi data penuh per workspace, dilengkapi RBAC empat peran (Owner, Admin, Member, Viewer).",
      "Login & registrasi via Google OAuth, plus sinkronisasi dua-arah dengan Google Calendar.",
      "Fitur inti: Notes ber-Markdown dan Kanban board drag-and-drop.",
      "Monetisasi bawaan: paket Basic / Standard / Pro dengan masa trial 14 hari.",
    ],
    results: [
      "SaaS B2B yang utuh end-to-end: dari autentikasi (Google OAuth), fitur produktivitas, sampai monetisasi (subscription + trial).",
      "Multi-tenant + RBAC siap melayani banyak workspace dengan data yang terisolasi aman.",
      "Kualitas kode terjaga lewat CI pipeline, laporan coverage (codecov), dan Go Report Card.",
    ],
    repoVisibility: "private",
    image: "/assets/images/projects/helixio.jpeg",
  },
  {
    slug: "rahan-mancar",
    title: "Rahan Mancar — Platform Website & CMS Multi-tenant",
    year: 2023,
    category: "Platform · CMS",
    tagline:
      "Headless CMS multi-tenant: kelola banyak website — blog, halaman, SEO, dan lead — dari satu backend Go.",
    summary:
      "Platform website multi-tenant dengan CMS, blog, modul SEO, dan lead-capture. Go hexagonal penuh (ports & adapters), i18n, dan worker async.",
    role: "Backend Engineer & Architect",
    timeframe: "2023",
    highlights: [
      "Hexagonal (Ports & Adapters)",
      "Multi-tenant",
      "CMS + Blog",
      "Modul SEO & Analytics",
      "Lead capture + Captcha",
      "i18n",
    ],
    stack: [
      "Go",
      "PostgreSQL",
      "Redis",
      "Next.js",
      "Worker queue (async)",
      "Object storage",
      "i18n",
    ],
    problem:
      "Agensi dan bisnis dengan banyak website company-profile butuh satu sistem untuk mengelola konten, blog, SEO, dan menangkap lead — tanpa harus membangun CMS dari nol untuk setiap klien.",
    solution: [
      "Backend Go hexagonal yang lengkap: domain dipisahkan dari adapter, dengan modul aplikasi terpisah untuk auth, blog, CMS, dashboard, analytics, SEO, lead, media, bahasa (i18n), tenant, user, dan website.",
      "Multi-tenant sejak fondasi — satu platform melayani banyak website dengan data masing-masing.",
      "Infrastruktur produksi: PostgreSQL, Redis, object storage untuk media, captcha anti-spam pada form lead, email untuk notifikasi lead, dan worker untuk pekerjaan async.",
      "Modul SEO dan Analytics bawaan, sehingga website klien siap-SEO dan terukur sejak hari pertama.",
      "Frontend Next.js yang terhubung ke API CMS.",
    ],
    results: [
      "Satu backend melayani banyak website dengan CMS, blog, SEO, dan lead-capture yang terpadu.",
      "Pola ports & adapters yang bersih membuat adapter (storage, email, captcha) bisa ditukar tanpa menyentuh domain.",
      "Lead-capture + analytics built-in mengubah website dari sekadar tampil menjadi mesin yang menghasilkan prospek.",
    ],
    repoVisibility: "private",
    image: "/assets/images/projects/rahanmancar-online.jpeg",
  },
] as const;

const caseStudyBySlug = new Map<string, CaseStudy>(
  caseStudies.map((c) => [c.slug, c]),
);

export function getCaseStudy(slug: string): CaseStudy | undefined {
  return caseStudyBySlug.get(slug);
}

export function getAllCaseStudySlugs(): readonly string[] {
  return caseStudies.map((c) => c.slug);
}
